<?php

/**
 * @file
 * Allows users to create and organize related content in an outline.
 */


/**
 * Implements hook_theme().
 */
function cart_theme($existing, $type, $theme, $path)
{
    return
        [
            'cart_index' => [
                'variables' => [
                    'sessionCart' => [],
                    'total' => "",
                    'point_total' => ""
                ]
            ],
        ];
}
