name: Product
type: module
description: 'Allows users to create and organize related content in an outline.'
package: Product

core_version_requirement: ^9
# version: VERSION
dependencies:
  - drupal:views
configure: product.settings

# Information added by Drupal.org packaging script on 2022-06-01
version: '9.4.7'
project: 'drupal'
datestamp: 1654098838